Force long CI tests to run to merge PRs

diff --git a/.github/workflows/pr_tests.yml b/.github/workflows/pr_tests.yml
--- a/.github/workflows/pr_tests.yml
+++ b/.github/workflows/pr_tests.yml
@@ -25,10 +25,14 @@ on:
 jobs:
   Reproducibility:
     runs-on: macos-latest
-    if: |
-      github.event_name == 'push' || github.event_name == 'merge_group' ||
-      contains(github.event.pull_request.labels.*.name, 'long ci')
     steps:
+    - name: Check for long ci label
+      if: github.event_name == 'pull_request'
+      run: |
+        if [[ "${{ contains(github.event.pull_request.labels.*.name, 'long ci') }}" != 'true' ]]; then
+          echo "Error: Add the 'long ci' label to this PR once it is ready for review."
+          exit 1
+        fi
     - uses: actions/checkout@v6
     - name: Install uv
       uses: astral-sh/setup-uv@v7
@@ -65,10 +69,14 @@ jobs:
         uv run --env-file .env runscripts/debug/diff_simouts.py -o "out" "parca_1*" "parca_2*"
   Two-gens:
     runs-on: macos-latest
-    if: |
-      github.event_name == 'push' || github.event_name == 'merge_group' ||
-      contains(github.event.pull_request.labels.*.name, 'long ci')
     steps:
+    - name: Check for long ci label
+      if: github.event_name == 'pull_request'
+      run: |
+        if [[ "${{ contains(github.event.pull_request.labels.*.name, 'long ci') }}" != 'true' ]]; then
+          echo "Error: Add the 'long ci' label to this PR once it is ready for review."
+          exit 1
+        fi
     - uses: actions/checkout@v6
     - name: Install uv
       uses: astral-sh/setup-uv@v7
